#!/usr/bin/env python3
"""spec_lint.py — traceability & consistency checker for the saltnitor-vnext spec pack.

Usage (from the repository root, or pass paths):
  python3 docs/specs/vnext/tools/spec_lint.py                 # check only (exit 1 on errors)
  python3 docs/specs/vnext/tools/spec_lint.py --sync          # regenerate Verify/Phase/Tasks + Appendix C, then check
  python3 docs/specs/vnext/tools/spec_lint.py --tests [--phase P3]
                                                             # also require `Verifies:` tags for every due MUST (T) AC
  python3 docs/specs/vnext/tools/spec_lint.py --list-phase P3  # verifier checklist: ACs first due in P3
Options:
  --req PATH       requirements.md (default: ../requirements.md from this file, or docs/specs/vnext/)
  --tasks PATH     tasks.md
  --progress PATH  PROGRESS.md (optional; checks that [x] tasks are logged)
  --src DIR        root scanned by --tests (default: current directory)

A task's **Reqs** line may cite a whole requirement (`REQ-SEC-002`: every AC) or single ACs
(`REQ-SEC-002/AC3`: only that AC). An AC is *due* at the first phase of any task that covers it.

Checks (REQ-DOC-006/AC1): undefined or retired IDs; references to missing ACs; MUST ACs covered by
no task; tasks without Reqs or Done-when; unknown, later-phase, or cyclic dependencies; `[P]` tasks
without Files, or overlapping/dependent `[P]` tasks in one phase; gate rows citing requirements
first due in a later phase; requirements without a source; `[x]` tasks without a PROGRESS.md
`DONE` line; stale generated fields. With --tests (REQ-TST-016/AC2): every due MUST AC verified
by `(T)` is cited by a `Verifies:` tag in a Rust, Python, shell, or CI-workflow file (Markdown is
never counted). Standard library only.
"""
from __future__ import annotations

import argparse
import collections
import fnmatch
import os
import re
import sys

REQ_HEAD = re.compile(r"^#### (REQ-[A-Z]+-\d{3}) — (.+)$", re.M)
META = re.compile(r"^> (MUST|SHOULD|MAY) · Verify: ([^·]+?) · Phase: ([^·]+?) · Tasks: ([^·]+?)((?: · .*)?)$")
AC_LINE = re.compile(r"^- \*\*AC(\d+)\*\*(.*)$")
AC_METHOD = re.compile(r"\(((?:T-HW|T|I|D|A)(?:\s*,\s*(?:T-HW|T|I|D|A))*)(?:\s+via\s+[^)]*)?\)")
METHOD_ORDER = ["T", "T-HW", "I", "D", "A"]
TASK_LINE = re.compile(r"^- \[([ x~!])\] \*\*(T\d+\.\d+(?:-fix-\d+)?) — (.+?)\*\*", re.M)
REQ_REF = re.compile(r"REQ-[A-Z]+-\d{3}(?:/AC\d+)?")
TASK_REF = re.compile(r"\bT\d+\.\d+(?:-fix-\d+)?\b")
GATE_HEAD = re.compile(r"^### Gate (G(\d+))\b.*$", re.M)
PHASE_OF = re.compile(r"^T(\d+)\.")
SOURCE_TOKEN = re.compile(r"Src:|BP §|TP §|\b(?:DEC|BD|INV|NG|OQ)-\d")
TAG_EXTENSIONS = (".rs", ".py", ".sh", ".bash", ".yml", ".yaml")
SKIP_DIRS = ("target", ".git", "node_modules")
APPENDIX_C = "## Appendix C — Coverage index (generated by `spec_lint.py --sync`; do not edit by hand)"


def read(path):
    with open(path, encoding="utf-8", errors="ignore") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def phase_key(p):
    return int(p[1:]) if p and p[0] == "P" and p[1:].isdigit() else 10**6


def task_key(t):
    return [int(n) for n in re.findall(r"\d+", t)]


def ac_methods(text):
    found = list(AC_METHOD.finditer(text))
    return {m.strip() for m in re.split(r"\s*,\s*", found[-1].group(1))} if found else set()


def ac_delegated(text):
    """True for '(T via REQ-…)': the AC is verified by another requirement's check."""
    found = list(AC_METHOD.finditer(text))
    return bool(found) and " via " in found[-1].group(0)


def should_level(text):
    return bool(re.search(r"\bSHOULD\b", text)) and not re.search(r"\bSHALL\b", text)


# ------------------------------------------------------------------ parsing

def parse_requirements(text):
    reqs = collections.OrderedDict()
    heads = list(REQ_HEAD.finditer(text))
    for i, m in enumerate(heads):
        rid, title = m.group(1), m.group(2).strip()
        end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
        body = text[m.end():end]
        cut = re.search(r"^#{2,3} ", body, re.M)
        if cut:
            end = m.end() + cut.start()
            body = body[:cut.start()]
        level = verify = meta_line = None
        rest = ""
        acs = collections.OrderedDict()
        for line in body.splitlines():
            s = line.strip()
            mm = META.match(s)
            if mm and meta_line is None:
                level, verify, rest, meta_line = mm.group(1), mm.group(2).strip(), mm.group(5), line
                continue
            am = AC_LINE.match(s)
            if am:
                acs[int(am.group(1))] = am.group(2)
        reqs[rid] = dict(title=title, retired=title.startswith("(retired"), level=level, verify=verify,
                         meta=meta_line, rest=rest, acs=acs, span=(m.start(), end))
    return reqs


def parse_tasks(text):
    tasks = collections.OrderedDict()
    matches = list(TASK_LINE.finditer(text))
    for i, m in enumerate(matches):
        status, tid, title = m.group(1), m.group(2), m.group(3)
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[m.start():end]
        for stop in ("\n### Gate", "\n<!-- /phase", "\n## "):
            j = body.find(stop)
            if j != -1:
                body = body[:j]
        first_line = body.split("\n", 1)[0]
        reqs_m = re.search(r"\*\*Reqs:\*\*\s*([^\n]+)", body)
        deps_m = re.search(r"\*\*Depends:\*\*\s*([^\n]+)", body)
        files_m = re.search(r"\*\*Files:\*\*\s*([^\n]+)", body)
        refs = REQ_REF.findall(reqs_m.group(1)) if reqs_m else REQ_REF.findall(first_line)
        cover = {}
        for ref in refs:
            base, _, ac = ref.partition("/AC")
            if not ac:
                cover[base] = None
            elif cover.get(base, set()) is not None:
                cover.setdefault(base, set()).add(int(ac))
        pm = PHASE_OF.match(tid)
        tasks[tid] = dict(status=status, title=title, cover=cover, refs=refs,
                          deps=set(TASK_REF.findall(deps_m.group(1))) if deps_m else set(),
                          files=re.findall(r"`([^`]+)`", files_m.group(1)) if files_m else None,
                          parallel="`[P]`" in first_line, phase=f"P{pm.group(1)}" if pm else None,
                          has_done="**Done when:**" in body, body=body)
    return tasks


def parse_gates(text):
    gates = collections.OrderedDict()
    heads = list(GATE_HEAD.finditer(text))
    for i, m in enumerate(heads):
        end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
        body = text[m.end():end]
        cut = re.search(r"\n\*\*(Claims to falsify|Evidence)", body)
        if cut:
            body = body[:cut.start()]
        refs = set()
        for row in re.findall(r"^\|.*\|\s*$", body, re.M):
            cells = [c.strip() for c in row.strip().strip("|").split("|")]
            if not cells or set(cells[0]) <= set("-: ") or cells[0] == "#":
                continue
            refs |= set(REQ_REF.findall(cells[-1]))
        gates[m.group(1)] = dict(phase=f"P{m.group(2)}", refs=refs)
    return gates


def appendix_g_areas(text):
    i = text.find("## Appendix G")
    if i == -1:
        return set()
    j = text.find("\n## ", i + 1)
    block = text[i:j if j != -1 else len(text)]
    return set(re.findall(r"\b([A-Z]{2,5})-(?:\*|\d{3})", block))


# ------------------------------------------------------------------ derived data

class Model:
    def __init__(self, req_text, tasks_text):
        self.req_text, self.tasks_text = req_text, tasks_text
        self.reqs = parse_requirements(req_text)
        self.tasks = parse_tasks(tasks_text)
        self.gates = parse_gates(tasks_text)
        self.by_req = collections.defaultdict(list)          # rid -> tasks citing any part
        for tid, t in self.tasks.items():
            for base in t["cover"]:
                self.by_req[base].append(tid)

    def ac_tasks(self, rid, n):
        return [t for t in self.by_req.get(rid, [])
                if self.tasks[t]["cover"][rid] is None or n in self.tasks[t]["cover"][rid]]

    def first_phase(self, tids):
        return min((self.tasks[t]["phase"] for t in tids), key=phase_key) if tids else None

    def ac_due(self, rid, n):
        return self.first_phase(self.ac_tasks(rid, n))

    def verify_field(self, rid):
        ms = set()
        for text in self.reqs[rid]["acs"].values():
            ms |= ac_methods(text)
        return ", ".join(m for m in METHOD_ORDER if m in ms) or (self.reqs[rid]["verify"] or "—")

    def tasks_field(self, rid):
        out = []
        for tid in sorted(self.by_req.get(rid, []), key=task_key):
            c = self.tasks[tid]["cover"][rid]
            out.append(tid if c is None else f"{tid} ({', '.join('AC%d' % n for n in sorted(c))})")
        return ", ".join(out) or "—"


def sync(model):
    req_text, tasks_text = model.req_text, model.tasks_text
    out, last = [], 0
    for rid, r in model.reqs.items():
        if r["retired"] or not r["meta"]:
            continue
        phase = model.first_phase(model.by_req.get(rid, [])) or "—"
        new_meta = (f"> {r['level']} · Verify: {model.verify_field(rid)} · Phase: {phase} · "
                    f"Tasks: {model.tasks_field(rid)}{r['rest']}")
        s, e = r["span"]
        out.append(req_text[last:s])
        out.append(req_text[s:e].replace(r["meta"], new_meta, 1))
        last = e
    out.append(req_text[last:])
    req_text = "".join(out)

    areas = collections.OrderedDict()
    for rid, r in model.reqs.items():
        if r["retired"]:
            continue
        s = areas.setdefault(rid.split("-")[1], collections.Counter())
        s[r["level"]] += 1
        if model.by_req.get(rid):
            s["covered_" + r["level"]] += 1
        if any(rid in g["refs"] for g in model.gates.values()):
            s["gated"] += 1
    lines = ["| Area | MUST (with task) | SHOULD (with task) | MAY | Cited by a gate row |", "|---|---|---|---|---|"]
    tot = collections.Counter()
    for a, s in areas.items():
        lines.append(f"| {a} | {s['MUST']} ({s['covered_MUST']}) | {s['SHOULD']} ({s['covered_SHOULD']}) | {s['MAY']} | {s['gated']} |")
        tot.update(s)
    lines.append(f"| **Total** | **{tot['MUST']} ({tot['covered_MUST']})** | **{tot['SHOULD']} ({tot['covered_SHOULD']})** | **{tot['MAY']}** | **{tot['gated']}** |")
    lines.append("")
    lines.append(f"Tasks: {len(model.tasks)} · Gates: {len(model.gates)} · Per-requirement task links (with AC scopes): "
                 "see the `Tasks:` field of each requirement.")
    i = tasks_text.find(APPENDIX_C)
    if i != -1:
        tasks_text = tasks_text[:i] + APPENDIX_C + "\n\n" + "\n".join(lines) + "\n"
    return req_text, tasks_text


# ------------------------------------------------------------------ checks

def ancestors(tasks, tid, seen=None):
    seen = set() if seen is None else seen
    for d in tasks[tid]["deps"]:
        if d in tasks and d not in seen:
            seen.add(d)
            ancestors(tasks, d, seen)
    return seen


def find_cycles(tasks):
    color, cycles = {}, []

    def visit(t, stack):
        color[t] = 1
        for d in tasks[t]["deps"]:
            if d not in tasks:
                continue
            if color.get(d) == 1:
                cycles.append(stack + [d])
            elif color.get(d) is None:
                visit(d, stack + [d])
        color[t] = 2

    for t in tasks:
        if color.get(t) is None:
            visit(t, [t])
    return cycles


def paths_overlap(a, b):
    def expand(p):
        m = re.search(r"\{([^}]+)\}", p)
        if not m:
            return {p.split(" ")[0]}
        return set().union(*(expand(p[:m.start()] + part + p[m.end():]) for part in m.group(1).split(",")))
    for x in a:
        for y in b:
            for xx in expand(x):
                for yy in expand(y):
                    if xx == yy or fnmatch.fnmatch(xx, yy) or fnmatch.fnmatch(yy, xx):
                        return xx
                    if (xx.endswith(("/", "/**")) and yy.startswith(xx.rstrip("*"))) or \
                       (yy.endswith(("/", "/**")) and xx.startswith(yy.rstrip("*"))):
                        return xx
    return None


def check(model, progress_text=None):
    reqs, tasks, gates = model.reqs, model.tasks, model.gates
    errors, warnings = [], []
    defined = {k for k, v in reqs.items() if not v["retired"]}
    retired = {k for k, v in reqs.items() if v["retired"]}
    g_areas = appendix_g_areas(model.req_text)

    # 1. requirement structure and sources
    for rid in defined:
        r = reqs[rid]
        if not r["meta"]:
            errors.append(f"{rid}: missing meta line '> LEVEL · Verify: … · Phase: … · Tasks: …'")
        if not r["acs"]:
            errors.append(f"{rid}: no acceptance criteria")
        for n, text in r["acs"].items():
            if not ac_methods(text):
                errors.append(f"{rid}/AC{n}: no verification method — end the AC with (T), (T-HW), (I), (D), or (A)")
        if r["meta"] and not SOURCE_TOKEN.search(r["rest"]) and rid.split("-")[1] not in g_areas:
            errors.append(f"{rid}: no source — add `Src: …` (or an INV/DEC/BD reference) or an Appendix G row for its area")

    # 2. references in both files
    for name, text in (("requirements.md", model.req_text), ("tasks.md", model.tasks_text)):
        for ref in sorted(set(REQ_REF.findall(text))):
            base = ref.split("/")[0]
            if base in retired and name == "tasks.md":
                errors.append(f"{name}: references retired {base} — use the requirement named in its stub")
            elif base not in defined and base not in retired:
                errors.append(f"{name}: undefined {ref}")
            elif "/AC" in ref and base in defined and int(ref.split("/AC")[1]) not in reqs[base]["acs"]:
                errors.append(f"{name}: {ref} — that AC does not exist")

    # 3. coverage, AC by AC
    for rid in sorted(defined):
        r = reqs[rid]
        if not model.by_req.get(rid):
            (errors if r["level"] == "MUST" else warnings).append(f"{rid}: {r['level']} requirement has no task")
            continue
        for n, text in r["acs"].items():
            if not model.ac_tasks(rid, n):
                msg = f"{rid}/AC{n}: covered by no task — cite it (or the whole requirement) in a task's Reqs"
                (errors if r["level"] == "MUST" and not should_level(text) else warnings).append(msg)

    # 4. tasks
    for tid, t in tasks.items():
        if not t["refs"]:
            errors.append(f"{tid}: no Reqs")
        if not t["has_done"]:
            errors.append(f"{tid}: no 'Done when'")
        for d in sorted(t["deps"]):
            if d not in tasks:
                errors.append(f"{tid}: depends on unknown {d}")
            elif phase_key(tasks[d]["phase"]) > phase_key(t["phase"]):
                errors.append(f"{tid}: depends on later-phase task {d}")
        if t["parallel"] and t["files"] is None:
            errors.append(f"{tid}: [P] task has no Files line (parallel tasks must declare disjoint files)")
    for cyc in find_cycles(tasks):
        errors.append(f"dependency cycle: {' → '.join(cyc)}")
    by_phase = collections.defaultdict(list)
    for tid, t in tasks.items():
        if t["parallel"]:
            by_phase[t["phase"]].append(tid)
    anc = {t: ancestors(tasks, t) for t in tasks}
    for ph, lst in by_phase.items():
        for i, a in enumerate(lst):
            for b in lst[i + 1:]:
                if a in anc[b] or b in anc[a]:
                    errors.append(f"{a}/{b}: both [P] but one depends on the other — drop [P] from one")
                ov = paths_overlap(tasks[a]["files"] or [], tasks[b]["files"] or [])
                if ov:
                    errors.append(f"{a}/{b}: [P] tasks share `{ov}` — make the files disjoint or drop [P]")

    # 5. gates
    for g, info in gates.items():
        if not info["refs"]:
            warnings.append(f"{g}: no requirement IDs in gate rows")
        for ref in sorted(info["refs"]):
            base = ref.split("/")[0]
            if base not in defined:
                continue
            if "/AC" in ref:
                due = model.ac_due(base, int(ref.split("/AC")[1])) if int(ref.split("/AC")[1]) in reqs[base]["acs"] else None
            else:
                due = model.first_phase(model.by_req.get(base, []))
            if due and phase_key(due) > phase_key(info["phase"]):
                errors.append(f"{g}: cites {ref}, which is first due in {due}")

    # 6. progress log for [x] tasks
    if progress_text is not None:
        for tid, t in tasks.items():
            if t["status"] == "x" and not re.search(rf"\b{re.escape(tid)}\b.*\bDONE\b", progress_text):
                errors.append(f"{tid}: ticked [x] but no 'DONE' line in PROGRESS.md")

    # 7. generated fields
    new_req, new_tasks = sync(model)
    if new_req != model.req_text or new_tasks != model.tasks_text:
        errors.append("generated Verify/Phase/Tasks fields or Appendix C are stale — run spec_lint.py --sync")
    return errors, warnings


def collect_tags(src):
    tags = collections.defaultdict(set)
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            if not f.endswith(TAG_EXTENSIONS):
                continue
            path = os.path.join(root, f)
            try:
                text = read(path)
            except OSError:
                continue
            for m in re.finditer(r"Verifies:\s*((?:REQ-[A-Z]+-\d{3}/AC\d+[,\s]*)+)", text):
                for ref in re.findall(r"REQ-[A-Z]+-\d{3}/AC\d+", m.group(1)):
                    tags[ref].add(path)
    return tags


def check_tests(model, src, phase):
    errors = []
    tags = collect_tags(src)
    limit = phase_key(phase) if phase else 10**6
    for rid in sorted(k for k, v in model.reqs.items() if not v["retired"] and v["level"] == "MUST"):
        for n, text in model.reqs[rid]["acs"].items():
            if "T" not in ac_methods(text) or should_level(text) or ac_delegated(text):
                continue
            due = model.ac_due(rid, n)
            if due and phase_key(due) <= limit and not tags.get(f"{rid}/AC{n}"):
                errors.append(f"{rid}/AC{n}: no test tagged 'Verifies: {rid}/AC{n}' (due {due})")
    return errors


def list_phase(model, phase):
    print(f"# Verifier checklist for G{phase[1:]}: acceptance criteria first due in {phase}")
    for rid, r in model.reqs.items():
        if r["retired"]:
            continue
        due = [n for n in r["acs"] if model.ac_due(rid, n) == phase]
        if due:
            print(f"- [ ] {rid} · {r['level']} · Verify: {model.verify_field(rid)} · {r['title']} · "
                  f"{', '.join('AC%d' % n for n in due)}")


# ------------------------------------------------------------------ main

def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--req")
    ap.add_argument("--tasks")
    ap.add_argument("--progress")
    ap.add_argument("--sync", action="store_true")
    ap.add_argument("--tests", action="store_true")
    ap.add_argument("--phase")
    ap.add_argument("--src", default=".")
    ap.add_argument("--list-phase", metavar="PHASE")
    a = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    cand = [os.path.join(here, ".."), os.path.join(os.getcwd(), "docs/specs/vnext"), here, os.getcwd()]

    def locate(name, given):
        if given:
            return given
        for c in cand:
            p = os.path.join(c, name)
            if os.path.exists(p):
                return os.path.normpath(p)
        sys.exit(f"spec_lint: cannot find {name}; pass --{'req' if name.startswith('req') else 'tasks'}")

    req_path, tasks_path = locate("requirements.md", a.req), locate("tasks.md", a.tasks)
    prog_path = a.progress or os.path.join(os.path.dirname(tasks_path), "PROGRESS.md")
    model = Model(read(req_path), read(tasks_path))

    if a.sync:
        new_req, new_tasks = sync(model)
        write(req_path, new_req)
        write(tasks_path, new_tasks)
        model = Model(new_req, new_tasks)

    if a.list_phase:
        list_phase(model, a.list_phase)
        return 0

    progress = read(prog_path) if os.path.exists(prog_path) else None
    errors, warnings = check(model, progress)
    if a.tests:
        errors += check_tests(model, a.src, a.phase)

    defined = [r for r in model.reqs.values() if not r["retired"]]
    print(f"spec_lint: {len(defined)} requirements ({sum(r['level'] == 'MUST' for r in defined)} MUST), "
          f"{len(model.reqs) - len(defined)} retired, {sum(len(r['acs']) for r in defined)} ACs, "
          f"{len(model.tasks)} tasks, {len(model.gates)} gates")
    for w in warnings:
        print(f"  warning: {w}")
    for e in errors:
        print(f"  ERROR: {e}")
    print("spec_lint: " + ("FAILED" if errors else "OK"))
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
